CSS_PROP_VALUES = {
 '-moz-binding'                  : [],
 '-moz-border-bottom-colors'     : [],
 '-moz-border-left-colors'       : [],
 '-moz-border-radius'            : [],
 '-moz-border-radius-bottomleft' : [],
 '-moz-border-radius-bottomright': [],
 '-moz-border-radius-topleft'    : [],
 '-moz-border-radius-topright'   : [],
 '-moz-border-right-colors'      : [],
 '-moz-border-top-colors'        : [],
 '-moz-opacity'                  : [],
 '-moz-outline'                  : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 '-moz-outline-color'            : [],
 '-moz-outline-style'            : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 '-moz-outline-width'            : ['thick', 'medium', '*', 'thin', 'inherit'],
 '-moz-user-focus'               : ['ignore', 'auto', 'none', 'inherit', 'normal'],
 '-moz-user-input'               : ['disabled', 'auto', 'none', 'enabled', 'inherit'],
 '-moz-user-modify'              : ['read-write', 'write-only', 'read-only', 'inherit'],
 '-moz-user-select'              : ['none', 'elements', 'text', 'all', 'inherit', 'element', 'toggle', 'tri-state'],
 '-o-link'                       : [],
 '-o-link-source'                : ['current', 'none', 'next'],
 'accelerator'                   : ['false', 'true', 'inherit'],
 'alignment-adjust'              : ['mathematical', 'ideographic', 'central', 'baseline', 'auto', 'alphabetic', '<length>', 'middle', '<percentage>', 'before-edge ', 'hanging', 'text-before-edge', 'text-after-edge', 'after-edge'],
 'alignment-baseline'            : ['mathematical', 'use-script', 'before-edge', 'central', 'baseline', 'hanging', 'ideographic', 'middle', 'alphabetic', 'text-before-edge', 'text-after-edge', 'after-edge'],
 'animation'                     : [],
 'animation-delay'               : [],
 'animation-direction'           : ['alternate', 'normal'],
 'animation-duration'            : [],
 'animation-iteration-count'     : [],
 'animation-name'                : [],
 'animation-play-state'          : [],
 'appearance'                    : [],
 'azimuth'                       : ['leftwards', 'right', 'center-left', 'center', 'right-side', '*', 'inherit', 'far-left', 'behind', 'far-right', 'center-right', 'left-side', 'rightwards', 'left'],
 'background'                    : ['no-repeat', 'none', 'right', 'center', 'bottom', 'top', '*', 'inherit', 'repeat', 'repeat-x', 'left', 'repeat-y', 'fixed', '#ffffff', 'scroll', 'url(image-url.gif)'],
 'background-attachment'         : ['fixed', 'scroll', 'inherit'],
 'background-clip'               : ['padding-box', 'border-box'],
 'background-color'              : [],
 'background-image'              : [],
 'background-origin'             : ['padding-box', 'border-box', 'content-box'],
 'background-position'           : ['right', 'center', 'bottom', 'top', '*', 'left'],
 'background-position-x'         : ['*', 'right', 'center', 'left'],
 'background-position-y'         : ['top', '*', 'center', 'bottom'],
 'background-repeat'             : ['no-repeat', 'repeat', 'repeat-x', 'repeat-y'],
 'background-size'               : ['cover', 'contain'],
 'baseline-shift'                : ['<length>', 'super', 'baseline', '<percentage>', 'sub'],
 'binding'                       : ['none', '<uri>'],
 'bookmark-label'                : [],
 'bookmark-level'                : [],
 'bookmark-target'               : [],
 'border'                        : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', '*', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'border-bottom'                 : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', '*', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'border-bottom-color'           : [],
 'border-bottom-left-radius'     : [],
 'border-bottom-right-radius'    : [],
 'border-bottom-style'           : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'border-bottom-width'           : ['thick', 'medium', '*', 'thin', 'inherit'],
 'border-collapse'               : ['collapse', 'inherit', 'separate'],
 'border-color'                  : [],
 'border-left'                   : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', '*', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'border-left-color'             : [],
 'border-left-style'             : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'border-left-width'             : ['thick', 'medium', '*', 'thin', 'inherit'],
 'border-length'                 : [],
 'border-radius'                 : [],
 'border-right'                  : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', '*', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'border-right-color'            : [],
 'border-right-style'            : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'border-right-width'            : ['thick', 'medium', '*', 'thin', 'inherit'],
 'border-spacing'                : [],
 'border-style'                  : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'border-top'                    : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', '*', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'border-top-color'              : [],
 'border-top-left-radius'        : [],
 'border-top-right-radius'       : [],
 'border-top-style'              : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'border-top-width'              : ['thick', 'medium', '*', 'thin', 'inherit'],
 'border-width'                  : ['thick', 'medium', '*', 'thin', 'inherit'],
 'bottom'                        : ['auto', '*', 'inherit'],
 'box-align'                     : ['stretch', 'start', 'end', 'center', 'baseline '],
 'box-direction'                 : ['reverse', 'normal'],
 'box-flex'                      : [],
 'box-flex-group'                : [],
 'box-lines'                     : ['single', 'multiple'],
 'box-ordinal-group'             : [],
 'box-orient'                    : ['inline-axis', 'horizontal', 'block-axis', 'vertical'],
 'box-pack'                      : ['start', 'end', 'center', 'justify'],
 'box-sizing'                    : ['content-box', 'border-box'],
 'caption-side'                  : ['top', 'left', 'right', 'inherit', 'bottom'],
 'clear'                         : ['both', 'none', 'right', 'all', 'inherit', 'left'],
 'clip'                          : ['auto', '*', 'inherit'],
 'color'                         : [],
 'color-profile'                 : ['auto', 'sRGB', '<url>', '<name>'],
 'column-count'                  : ['auto', '<integer>'],
 'column-fill'                   : ['auto', 'balance'],
 'column-gap'                    : ['<length>', 'normal'],
 'column-rule-color'             : [],
 'column-rule-style'             : [],
 'column-rule-width'             : [],
 'column-span'                   : ['1', 'all'],
 'column-width'                  : ['auto', '<length>'],
 'columns'                       : [],
 'columns-rule'                  : [],
 'content'                       : ['no-close-quote', 'close-quote', '*', 'inherit', 'no-open-quote', 'open-quote'],
 'counter-increment'             : ['upper-latin', 'none', 'decimal-leading-zero', 'lower-roman', 'lower-greek', 'decimal', '*', 'inherit', 'lower-latin', 'upper-roman'],
 'counter-reset'                 : ['none', '*', 'inherit'],
 'crop'                          : ['auto', 'rect(top, right, bottom, left)', 'inset-rect(top, right, bottom, left)'],
 'cue'                           : [],
 'cue-after'                     : [],
 'cue-before'                    : [],
 'cursor'                        : ['sw-resize', 'move', 's-resize', 'help', 'e-resize', 'default', 'auto', 'w-resize', '*', 'inherit', 'hand', 'ne-resize', 'n-resize', 'crosshair', 'text', 'se-resize', 'progress', 'nw-resize', 'pointer', 'wait'],
 'direction'                     : ['ltr', 'inherit', 'rtl'],
 'display'                       : ['compact', 'inline-table', 'table-row-group', 'table-header-group', 'inline-block', 'table-footer-group', 'run-in', 'none', 'inherit', 'table-cell', 'list-item', 'table-row', 'table-caption', 'table-column', 'marker', 'inline', 'table', 'block', 'table-column-group'],
 'dominant-baseline'             : ['mathematical', 'use-script', 'ideographic', 'central', 'reset-size', 'auto', 'alphabetic', 'middle', 'hanging', 'text-before-edge', 'text-after-edge', 'no-change'],
 'drop-initial-after-adjust'     : ['mathematical', 'before-edge', 'central', '<length>', 'middle', '<percentage>', 'hanging', 'text-before-edge'],
 'drop-initial-after-align'      : ['mathematical', 'use-script', 'before-edge', 'central', 'baseline', 'hanging', 'ideographic', 'middle', 'alphabetic', 'text-before-edge', 'text-after-edge', 'after-edge'],
 'drop-initial-before-adjust'    : ['mathematical', 'before-edge', 'central', '<length>', 'middle', '<percentage>', 'hanging', 'text-before-edge'],
 'drop-initial-before-align'     : ['mathematical', 'use-script', 'before-edge', 'central', 'baseline', 'hanging', 'ideographic', 'middle', 'caps-height', 'alphabetic', 'text-before-edge', 'text-after-edge', 'after-edge'],
 'drop-initial-size'             : ['<percentage>', 'auto', '<length>', '<line>'],
 'drop-initial-value'            : ['<integer>', 'initial'],
 'elevation'                     : ['lower', 'level', '*', 'inherit', 'below', 'above', 'higher'],
 'empty-cells'                   : ['hide', 'inherit', 'show'],
 'filter'                        : [],
 'fit'                           : ['meet', 'hidden', 'slice', 'fill'],
 'fit-position'                  : [],
 'float'                         : ['none', 'right', 'inherit', 'left'],
 'font'                          : ['"Bodoni MT Condensed"', '"Eras Light ITC"', 'Arial', '"Franklin Gothic Heavy"', '"MS Reference Sans Serif"', 'Haettenschweiler', 'oblique', 'Helvetica', '"Franklin Gothic Book"', '"Franklin Gothic Medium Cond"', '"Gill Sans MT Condensed"', 'Elephant', 'semi-expanded', 'ZWAdobeF', '"Microsoft Sans Serif"', '300', 'Shruti', '"Engravers MT"', 'Perpetua', '"Courier New", Courier, monospace', '400', 'Sylfaen', 'extra-expanded', '"Felix Titling"', 'bolder', '"Tw Cen MT"', 'WST_Swed', 'Verdana', 'lighter', 'Monaco', '"Lucida Sans"', '"Script MT Bold"', '"Zapf Dingbats"', 'large', 'small', '"Bradley Hand ITC"', '"Rockwell Extra Bold"', 'Fixedsys', 'extra-condensed', 'Impact', 'smaller', '"Bookman Old Style"', '"Eras Demi ITC"', '"Comic Sans MS"', '"Bodoni MT Black"', '700', 'System', 'Arial, Helvetica, sans-serif', '"Arial Rounded MT Bold"', 'Gigi', 'ultra-expanded', '"MS Sans Serif"', '"SF Collegiate Solid"', 'bold', 'Charcoal', '"Imprint MT Shadow"', 'Gadget', 'x-small', 'Webdings', '"Bodoni MT"', 'Gautami', '"Edwardian Script ITC"', 'condensed', 'Tahoma', 'monospace', 'Times', 'Nina', 'Marlett', '"Goudy Old Style"', 'WST_Span', '100', '"MS Sans Serif", Geneva, sans-serif', 'cursive', '"Calisto MT"', '900', '"Curlz MT"', '"Tw Cen MT Condensed"', 'Vrinda', '"Century Gothic"', 'larger', '"Gill Sans MT"', 'Verdana, Geneva, Arial, Helvetica, sans-serif', '"OCR A Extended"', 'small-caps', 'WST_Germ', '"Monotype Corsiva"', 'narrower', 'number', '"MS Serif"', 'fantasy', '"Rockwell Condensed"', 'wider', '"Estrangelo Edessa"', 'Pristina', '"Arial Black"', 'Garamond', 'Courier', 'x-large', 'Symbol', '*', '"Perpetua Titling MT"', '"Eras Medium ITC"', 'italic', '"Tw Cen MT Condensed Extra Bold"', '"Times New Roman", Times, serif', '500', 'Georgia', '"Gill Sans MT Ext Condensed Bold"', '"Lucida Sans Typewriter"', '"Palatino Linotype"', 'Default', '"Lucida Grande"', 'Raavi', '"Agency FB"', '"Arial Narrow"', 'serif', '"SF Collegiate"', '"MV Boli"', '"Copperplate Gothic Light"', 'xx-small', 'none', '"Copperplate Gothic Bold"', 'Forte', 'ultra-condensed', '"Rage Italic"', 'expanded', 'Latha', '"Gloucester MT Extra Condensed"', '"Blackadder ITC"', 'semi-condensed', '"MS Serif", "New York", serif', '"Franklin Gothic Medium"', '"New York"', 'Palatino Linotype', '600', 'Castellar', '"French Script MT"', '"Gill Sans Ultra Bold Condensed"', 'xx-large', '"Franklin Gothic Demi Cond"', 'Terminal', '"Courier New"', 'medium', '"MS Reference Specialty"', 'Collegiate-Normal', 'Wingdings', '"Bookshelf Symbol 7"', '"Franklin Gothic Demi"', '"Trebuchet MS"', '"Wingdings 2"', 'WST_Ital', 'Geneva', 'Rockwell', 'WST_Engl', 'Kartika', 'Script', '"Times New Roman"', '200', '"Eras Bold ITC"', 'normal', 'Tunga', 'Papyrus', 'WST_Czec', '"Small Fonts"', '"Lucida Console"', 'Roman', '"MS Outlook"', '"Gill Sans Ultra Bold"', 'Futura', '"Book Antiqua"', '"Wingdings 3"', 'Mangal', '"Maiandra GD"', '"Lucida Sans Unicode"', 'Modern', 'inherit', 'sans-serif', '"Goudy Stout"', 'WST_Fren', '800', '"Palace Script MT"'],
 'font-family'                   : ['"Bodoni MT Condensed"', '"Eras Light ITC"', 'Arial', '"Franklin Gothic Heavy"', '"MS Reference Sans Serif"', 'Haettenschweiler', 'Helvetica', '"Franklin Gothic Book"', '"Franklin Gothic Medium Cond"', '"Gill Sans MT Condensed"', 'Elephant', 'ZWAdobeF', '"Microsoft Sans Serif"', 'Shruti', '"Engravers MT"', 'Perpetua', '"Courier New", Courier, monospace', 'Sylfaen', '"Felix Titling"', '"Tw Cen MT"', 'WST_Swed', 'Verdana', 'Monaco', '"Lucida Sans"', '"Script MT Bold"', '"Zapf Dingbats"', '"Bradley Hand ITC"', '"Rockwell Extra Bold"', 'Fixedsys', 'Impact', '"Bookman Old Style"', '"Eras Demi ITC"', '"Comic Sans MS"', '"Bodoni MT Black"', 'System', 'Arial, Helvetica, sans-serif', '"Arial Rounded MT Bold"', 'Gigi', '"MS Sans Serif"', '"SF Collegiate Solid"', 'Charcoal', '"Imprint MT Shadow"', 'Gadget', 'Webdings', '"Bodoni MT"', 'Gautami', '"Edwardian Script ITC"', 'Tahoma', 'monospace', 'Times', 'Nina', 'Marlett', '"Goudy Old Style"', 'WST_Span', '"MS Sans Serif", Geneva, sans-serif', 'cursive', '"Calisto MT"', '"Curlz MT"', '"Tw Cen MT Condensed"', 'Vrinda', '"Century Gothic"', '"Gill Sans MT"', 'Verdana, Geneva, Arial, Helvetica, sans-serif', '"OCR A Extended"', 'WST_Germ', '"Monotype Corsiva"', '"MS Serif"', 'fantasy', '"Rockwell Condensed"', '"Estrangelo Edessa"', 'Pristina', '"Arial Black"', 'Garamond', 'Courier', 'Symbol', '*', '"Perpetua Titling MT"', '"Eras Medium ITC"', '"Tw Cen MT Condensed Extra Bold"', '"Times New Roman", Times, serif', 'Georgia', '"Gill Sans MT Ext Condensed Bold"', '"Lucida Sans Typewriter"', '"Palatino Linotype"', 'Default', '"Lucida Grande"', 'Raavi', '"Agency FB"', '"Arial Narrow"', 'serif', '"SF Collegiate"', '"MV Boli"', '"Copperplate Gothic Light"', '"Copperplate Gothic Bold"', 'Forte', '"Rage Italic"', 'Latha', '"Gloucester MT Extra Condensed"', '"Blackadder ITC"', '"MS Serif", "New York", serif', '"Franklin Gothic Medium"', '"New York"', 'Palatino Linotype', 'Castellar', '"French Script MT"', '"Gill Sans Ultra Bold Condensed"', '"Franklin Gothic Demi Cond"', 'Terminal', '"Courier New"', '"MS Reference Specialty"', 'Collegiate-Normal', 'Wingdings', '"Bookshelf Symbol 7"', '"Franklin Gothic Demi"', '"Trebuchet MS"', '"Wingdings 2"', 'WST_Ital', 'Geneva', 'Rockwell', 'WST_Engl', 'Kartika', 'Script', '"Times New Roman"', '"Eras Bold ITC"', 'Tunga', 'Papyrus', 'WST_Czec', '"Small Fonts"', '"Lucida Console"', 'Roman', '"MS Outlook"', '"Gill Sans Ultra Bold"', 'Futura', '"Book Antiqua"', '"Wingdings 3"', 'Mangal', '"Maiandra GD"', '"Lucida Sans Unicode"', 'Modern', 'inherit', 'sans-serif', '"Goudy Stout"', 'WST_Fren', '"Palace Script MT"'],
 'font-size'                     : ['smaller', 'x-large', '*', 'inherit', 'large', 'medium', 'xx-large', 'larger', 'small', 'xx-small', 'x-small'],
 'font-size-adjust'              : [],
 'font-stretch'                  : ['condensed', 'normal', 'ultra-condensed', 'expanded', 'narrower', 'semi-condensed', 'extra-condensed', 'ultra-expanded', 'wider', 'semi-expanded', 'extra-expanded'],
 'font-style'                    : ['oblique', 'italic', 'inherit', 'normal'],
 'font-variant'                  : ['small-caps', 'inherit', 'normal'],
 'font-weight'                   : ['200', '900', 'bold', 'bolder', 'normal', '300', '700', 'inherit', 'lighter', '400', '100', '800', '500', '600'],
 'hanging-punctuation'           : ['start', 'end', 'end-edge'],
 'height'                        : ['auto', '*', 'inherit'],
 'hyphenate-after'               : [],
 'hyphenate-before'              : [],
 'hyphenate-lines'               : [],
 'hyphenate-resource'            : [],
 'hyphens'                       : ['auto', 'none', 'manual'],
 'icon'                          : ['auto', '<uri>'],
 'image-orientation'             : ['auto', '<angle>'],
 'image-resolution'              : ['<dpi>', 'auto', 'normal'],
 'ime-mode'                      : ['active', 'auto', 'inactive', 'disabled'],
 'inline-box-align'              : ['<integer>', 'initial', 'last'],
 'layout-flow'                   : ['vertical-ideographic', 'horizontal'],
 'layout-grid'                   : ['vertical-ideographic', 'horizontal'],
 'layout-grid-char'              : ['auto', 'none', '*'],
 'layout-grid-line'              : ['auto', 'none', '*'],
 'layout-grid-mode'              : ['char', 'both', 'none', 'line'],
 'layout-grid-type'              : ['strict', 'loose', 'fixed'],
 'left'                          : ['auto', '*', 'inherit'],
 'letter-spacing'                : ['*', 'inherit', 'normal'],
 'line-break'                    : ['strict', 'normal'],
 'line-height'                   : ['*', 'inherit', 'normal'],
 'line-stacking'                 : [],
 'line-stacking-ruby'            : ['exclude-ruby', 'include-ruby'],
 'line-stacking-shift'           : ['disregard-shifts', 'consider-shifts'],
 'line-stacking-strategy'        : ['max-height', 'block-line-height', 'inline-line-height', 'grid-height'],
 'list-style'                    : ['square', 'disc', 'lower-latin', 'hebrew', 'katakana', 'hiragana-iroha', 'upper-alpha', 'upper-latin', 'hiragana', 'outside', 'circle', 'upper-roman', 'georgian', 'katakana-iroha', 'lower-alpha', 'armenian', 'cjk-ideographic', 'none', 'lower-roman', 'lower-greek', 'inside', 'decimal-leading-zero', 'inherit', 'decimal', 'url(image-url.gif)'],
 'list-style-image'              : [],
 'list-style-position'           : ['inside', 'outside', 'inherit'],
 'list-style-type'               : ['square', 'disc', 'lower-latin', 'hebrew', 'katakana', 'hiragana-iroha', 'upper-alpha', 'upper-latin', 'hiragana', 'circle', 'upper-roman', 'georgian', 'katakana-iroha', 'lower-alpha', 'armenian', 'cjk-ideographic', 'none', 'lower-roman', 'lower-greek', 'decimal', 'decimal-leading-zero', 'inherit'],
 'margin'                        : [],
 'margin-bottom'                 : [],
 'margin-left'                   : [],
 'margin-right'                  : [],
 'margin-top'                    : [],
 'mark'                          : [],
 'mark-after'                    : [],
 'mark-before'                   : [],
 'marker-offset'                 : [],
 'marks'                         : ['none', 'crop', 'inherit', 'cross'],
 'marquee-direction'             : ['forward', 'reverse'],
 'marquee-play-count'            : [],
 'marquee-speed'                 : ['slow', 'fast', 'normal'],
 'marquee-style'                 : ['slide', 'alternate', 'scroll'],
 'max-height'                    : [],
 'max-width'                     : [],
 'min-height'                    : [],
 'min-width'                     : [],
 'move-to'                       : ['<identifier>', 'here', 'normal'],
 'nav-down'                      : ['<target-name>', 'auto', '<id>'],
 'nav-index'                     : ['auto', '<number>'],
 'nav-left'                      : ['<target-name>', 'auto', '<id>'],
 'nav-up'                        : ['<target-name>', 'auto', '<id>'],
 'opacity'                       : [],
 'orphans'                       : [],
 'outline'                       : ['none', 'groove', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'medium', 'thin', 'double', 'hidden', '#ffffff', 'thick'],
 'outline-color'                 : [],
 'outline-offset'                : [],
 'outline-style'                 : ['none', 'ridge', 'dotted', 'solid', 'dashed', 'outset', 'inherit', 'inset', 'double', 'hidden', 'groove'],
 'outline-width'                 : ['thick', 'medium', '*', 'thin', 'inherit'],
 'overflow'                      : ['visible', 'hidden', 'scroll', 'inherit', 'auto'],
 'overflow-style'                : ['auto', 'marquee-line', 'marquee-block'],
 'overflow-x'                    : ['visible', 'hidden', 'scroll', 'inherit', 'auto'],
 'overflow-y'                    : ['visible', 'hidden', 'scroll', 'inherit', 'auto'],
 'padding'                       : [],
 'padding-bottom'                : [],
 'padding-left'                  : [],
 'padding-right'                 : [],
 'padding-top'                   : [],
 'page'                          : [],
 'page-break-after'              : ['right', 'auto', 'avoid', 'inherit', 'always', 'left'],
 'page-break-before'             : ['right', 'auto', 'avoid', 'inherit', 'always', 'left'],
 'page-break-inside'             : ['always', 'avoid', 'inherit', 'auto'],
 'page-policy'                   : ['start', 'last', 'first'],
 'pause'                         : [],
 'pause-after'                   : [],
 'pause-before'                  : [],
 'phonemes'                      : [],
 'pitch'                         : ['x-low', 'medium', 'inherit', 'high', 'low', 'x-high'],
 'pitch-range'                   : [],
 'play-during'                   : ['mix', 'none', 'repeat', 'inherit', 'auto'],
 'position'                      : ['relative', 'fixed', 'static', 'inherit', 'absolute'],
 'presentation-level'            : ['<integer>', 'increment', 'same'],
 'punctuation-trim'              : ['start', 'none', 'end', 'adjacent'],
 'quotes'                        : [],
 'rendering-intent'              : [],
 'resize'                        : ['both', 'none', 'horizontal', 'vertical'],
 'rest'                          : [],
 'rest-after'                    : ['x-strong', 'none', 'medium', 'weak', '<length>', 'strong', 'x-weak'],
 'rest-before'                   : ['x-strong', 'none', 'medium', 'weak', '<length>', 'strong', 'x-weak'],
 'richness'                      : [],
 'right'                         : ['auto', '*', 'inherit'],
 'rotation'                      : [],
 'rotation-point'                : [],
 'ruby-align'                    : ['right', 'center', 'auto', 'distribute-space', 'line-edge', 'inherit', 'distribute-letter', 'left'],
 'ruby-overhang'                 : ['auto', 'none', 'whitespace'],
 'ruby-position'                 : ['inline', 'above'],
 'ruby-span'                     : ['none', 'attr(x)'],
 'scrollbar-3dlight-color'       : [],
 'scrollbar-arrow-color'         : [],
 'scrollbar-base-color'          : [],
 'scrollbar-darkshadow-color'    : [],
 'scrollbar-face-color'          : [],
 'scrollbar-highlight-color'     : [],
 'scrollbar-shadow-color'        : [],
 'scrollbar-track-color'         : [],
 'size'                          : ['auto', '*', 'landscape', 'portrait'],
 'speak'                         : ['none', 'spell-out', 'inherit', 'normal'],
 'speak-header'                  : ['always', 'inherit', 'once'],
 'speak-numeral'                 : ['digits', 'continuous', 'inherit'],
 'speak-punctuation'             : ['none', 'code', 'inherit'],
 'speech-rate'                   : ['slow', 'x-slow', 'x-fast', '*', 'fast', 'medium', 'inherit', 'slower', 'faster'],
 'stress'                        : [],
 'string-set'                    : [],
 'table-layout'                  : ['auto', 'fixed', 'inherit'],
 'target'                        : [],
 'target-name'                   : ['<string>', 'parent ', 'current', 'modal', 'new', 'root'],
 'target-new'                    : ['window', 'none', 'tab'],
 'target-position'               : ['front', 'behind', 'back', 'above'],
 'text-align'                    : ['right', 'justify', 'center', 'inherit', 'left'],
 'text-align-last'               : ['right', 'center', 'auto', 'inherit', 'left', 'justify'],
 'text-decoration'               : ['none', 'inherit', 'blink', 'overline', 'line-through', 'underline'],
 'text-emphasis'                 : ['none', 'after', 'accent', 'disc', 'circle', 'dot', 'before'],
 'text-height'                   : ['max-size', 'auto', 'font-size', 'text-size'],
 'text-indent'                   : [],
 'text-justify'                  : ['newspaper', 'inter-ideograph', 'inter-word', 'distribute-center-last', 'auto', 'distribute', 'distribute-all-lines', 'inter-cluster', 'kashida'],
 'text-outline'                  : [],
 'text-overflow'                 : ['ellipsis', 'clip'],
 'text-replace'                  : [],
 'text-shadow'                   : [],
 'text-transform'                : ['uppercase', 'lowercase', 'capitalize', 'none', 'inherit'],
 'text-underline-position'       : ['auto', 'below', 'auto-pos', 'above'],
 'text-wrap'                     : ['uppercase', 'lowercase', 'capitalize', 'none'],
 'top'                           : ['auto', '*', 'inherit'],
 'transition'                    : [],
 'transition-delay'              : [],
 'transition-duration'           : [],
 'transition-property'           : [],
 'unicode-bidi'                  : ['embed', 'bidi-override', 'inherit', 'normal'],
 'vertical-align'                : ['text-top', 'sub', 'bottom', 'text-bottom', 'top', '*', 'inherit', 'middle', 'super', 'baseline'],
 'visibility'                    : ['visible', 'hidden', 'collapse', 'inherit'],
 'voice-balance'                 : ['right', 'center', '<length>', 'leftwards', 'rightwards', 'left'],
 'voice-duration'                : ['<time>'],
 'voice-family'                  : ['*', 'male', 'female', 'child'],
 'voice-pitch'                   : ['x-low', 'medium', 'high', '<number>', 'low', '<percentage>', 'x-high'],
 'voice-pitch-range'             : ['x-low', 'medium', 'high', '<number>', 'low', '<percentage>', 'x-high'],
 'voice-rate'                    : ['medium', 'x-slow', 'x-fast', 'fast', 'slow', '<percentage>'],
 'voice-stress'                  : ['none', 'moderate', 'reduced', 'strong'],
 'voice-volume'                  : ['medium', 'soft', 'x-loud', '<number>', '<percentage>', 'x-soft', 'loud'],
 'volume'                        : ['medium', 'silent', 'soft', '*', 'x-loud', 'x-soft', 'loud'],
 'white-space'                   : ['pre', 'pre-wrap', 'pre-line', 'nowrap', 'normal'],
 'white-space-collapse'          : ['preserve', 'discard', 'collapse', 'preserve-breaks'],
 'widows'                        : [],
 'width'                         : ['auto', '*', 'inherit'],
 'word-break'                    : ['keep-all', 'break-all', 'normal'],
 'word-spacing'                  : [],
 'word-wrap'                     : ['break-word', 'normal'],
 'writing-mode'                  : ['tb-rl', 'lr-tb'],
 'z-index'                       : [],
 'zoom'                          : ['*', 'normal']}

HTML_ELEMENTS_ATTRIBUTES = {
 'a'         : ['methods', 'accesskey', 'hreflang', 'disabled', 'datafld', 'shape', 'href', 'id', 'hidefocus', 'style', 'title', 'unselectable', 'charset', 'rev', 'rel', 'type', 'class', 'target', 'lang', 'contenteditable', 'name', 'language', 'urn', 'datasrc', 'coords', 'dir', 'tabindex'],
 'abbr'      : ['lang', 'style', 'title', 'id', 'class', 'dir'],
 'acronym'   : ['lang', 'style', 'title', 'id', 'class', 'dir'],
 'address'   : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'applet'    : ['code', 'accesskey', 'height', 'datafld', 'alt', 'hspace', 'id', 'hidefocus', 'style', 'title', 'unselectable', 'archive', 'width', 'object', 'codebase', 'class', 'src', 'name', 'align', 'datasrc', 'vspace', 'mayscript', 'tabindex'],
 'area'      : ['lang', 'hidefocus', 'style', 'target', 'title', 'unselectable', 'accesskey', 'id', 'nohref', 'shape', 'href', 'coords', 'alt', 'class', 'dir', 'tabindex'],
 'article'   : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'aside'     : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'audio'     : ['lang', 'preload', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'controls', 'id', 'draggable', 'tabindex', 'loop', 'spellcheck', 'hidden', 'src', 'class', 'dir', 'autoplay'],
 'b'         : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'base'      : ['href', 'id', 'target'],
 'basefont'  : ['color', 'size', 'id', 'face'],
 'bdo'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'bgsound'   : ['volume', 'src', 'balance', 'id', 'loop'],
 'big'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'blink'     : ['lang', 'style', 'class', 'id'],
 'blockquote': ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'cite', 'dir', 'tabindex'],
 'body'      : ['text', 'accesskey', 'disabled', 'bgproperties', 'nowrap', 'id', 'hidefocus', 'style', 'vlink', 'title', 'unselectable', 'bgcolor', 'bottommargin', 'alink', 'link', 'background', 'marginheight', 'class', 'lang', 'contenteditable', 'language', 'rightmargin', 'marginwidth', 'tabindex', 'scroll', 'dir', 'leftmargin'],
 'br'        : ['title', 'clear', 'style', 'class', 'id'],
 'button'    : ['lang', 'dataformatas', 'style', 'contenteditable', 'name', 'language', 'hidefocus', 'accesskey', 'title', 'datasrc', 'value', 'id', 'datafld', 'type', 'class', 'tabindex'],
 'canvas'    : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'height', 'draggable', 'width', 'id', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'caption'   : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'valign', 'id', 'align', 'dir', 'tabindex'],
 'center'    : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'cite'      : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'code'      : ['lang', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'id', 'disabled', 'class', 'dir'],
 'col'       : ['lang', 'style', 'span', 'title', 'align', 'id', 'char', 'bgcolor', 'width', 'valign', 'charoff', 'class', 'dir'],
 'colgroup'  : ['lang', 'style', 'span', 'title', 'align', 'id', 'char', 'bgcolor', 'width', 'valign', 'charoff', 'class', 'dir'],
 'command'   : ['lang', 'draggable', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'spellcheck', 'height', 'disabled', 'width', 'tabindex', 'radiogroup', 'id', 'checked', 'hidden', 'label', 'type', 'class', 'dir', 'icon'],
 'comment'   : ['lang', 'data', 'id', 'title'],
 'datalist'  : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'dd'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'nowrap', 'class', 'dir', 'tabindex'],
 'del'       : ['lang', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'datetime', 'disabled', 'class', 'id', 'cite', 'dir', 'tabindex'],
 'details'   : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'open', 'class', 'dir', 'tabindex'],
 'dfn'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'dir'       : ['hidefocus', 'contenteditable', 'language', 'unselectable', 'accesskey', 'disabled', 'dir', 'tabindex'],
 'div'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'nowrap', 'align', 'dir', 'tabindex'],
 'dl'        : ['compact', 'hidefocus', 'style', 'contenteditable', 'lang', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'dt'        : ['compact', 'hidefocus', 'style', 'contenteditable', 'lang', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'nowrap', 'class', 'dir', 'tabindex'],
 'em'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'embed'     : ['code', 'accesskey', 'height', 'style', 'alt', 'hspace', 'id', 'palette', 'title', 'unselectable', 'border', 'width', 'units', 'hidden', 'type', 'pluginspage', 'codebase', 'class', 'src', 'name', 'language', 'align', 'vspace'],
 'fieldset'  : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'datafld', 'id', 'align', 'dir', 'tabindex'],
 'figcaption': ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'figure'    : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'font'      : ['lang', 'hidefocus', 'style', 'contenteditable', 'weight', 'language', 'title', 'color', 'unselectable', 'accesskey', 'face', 'disabled', 'id', 'point-size', 'tabindex', 'class', 'dir', 'size'],
 'footer'    : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'form'      : ['lang', 'disabled', 'style', 'contenteditable', 'name', 'language', 'hidefocus', 'unselectable', 'title', 'id', 'autocomplete', 'accept-charset', 'target', 'action', 'method', 'tabindex', 'class', 'dir', 'enctype'],
 'frame'     : ['height', 'datafld', 'width', 'id', 'hidefocus', 'style', 'title', 'unselectable', 'application', 'bordercolor', 'noresize', 'allowtransparency', 'marginheight', 'scrolling', 'class', 'frameborder', 'lang', 'name', 'language', 'datasrc', 'marginwidth', 'security', 'longdesc', 'tabindex'],
 'frameset'  : ['bordercolor', 'hidefocus', 'style', 'rows', 'lang', 'language', 'title', 'unselectable', 'cols', 'framespacing', 'id', 'longdesc', 'border', 'class', 'frameborder', 'tabindex'],
 'h1'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'h2'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'h3'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'h4'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'h5'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'h6'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'head'      : ['lang', 'profile', 'class', 'dir', 'id'],
 'header'    : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'hgroup'    : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'hr'        : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'class', 'align', 'noshade', 'tabindex', 'id', 'dir', 'size'],
 'html'      : ['lang', 'xmlns', 'class', 'id', 'scroll', 'dir'],
 'i'         : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'iframe'    : ['height', 'datafld', 'width', 'hspace', 'id', 'hidefocus', 'style', 'title', 'unselectable', 'application', 'bordercolor', 'allowtransparency', 'marginheight', 'scrolling', 'class', 'frameborder', 'lang', 'src', 'name', 'language', 'align', 'datasrc', 'vspace', 'marginwidth', 'security', 'longdesc', 'tabindex'],
 'ilayer'    : ['src', 'style', 'above', 'clip', 'name', 'top', 'z-index', 'visibility', 'height', 'width', 'below', 'background', 'pagey', 'id', 'pagex', 'class', 'left'],
 'img'       : ['accesskey', 'height', 'datafld', 'usemap', 'alt', 'hspace', 'id', 'hidefocus', 'style', 'galleryimg', 'title', 'border', 'width', 'ismap', 'class', 'lang', 'src', 'lowsrc', 'language', 'align', 'datasrc', 'vspace', 'dynsrc', 'dir', 'unselectable', 'longdesc', 'loop', 'tabindex'],
 'input'     : ['accesskey', 'accept', 'disabled', 'alt', 'hspace', 'id', 'size', 'hidefocus', 'style', 'checked', 'title', 'unselectable', 'readonly', 'type', 'class', 'name', 'lang', 'src', 'language', 'lowsrc', 'align', 'value', 'autocomplete', 'vspace', 'dynsrc', 'dir', 'maxlength', 'loop', 'tabindex'],
 'ins'       : ['lang', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'datetime', 'disabled', 'class', 'id', 'cite', 'dir', 'tabindex'],
 'isindex'   : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'href', 'action', 'class', 'dir', 'tabindex'],
 'kbd'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'keygen'    : ['lang', 'draggable', 'keytype', 'hidden', 'contenteditable', 'name', 'form', 'contextmenu', 'challenge', 'title', 'style', 'class', 'disabled', 'id', 'spellcheck', 'autofocus', 'accesskey', 'dir', 'tabindex'],
 'label'     : ['lang', 'dataformatas', 'style', 'contenteditable', 'language', 'for', 'hidefocus', 'unselectable', 'accesskey', 'title', 'datasrc', 'id', 'disabled', 'datafld', 'class', 'dir', 'tabindex'],
 'layer'     : ['style', 'above', 'clip', 'title', 'name', 'top', 'z-index', 'visibility', 'height', 'bgcolor', 'below', 'width', 'background', 'pagey', 'id', 'overflow', 'pagex', 'class', 'left'],
 'legend'    : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'li'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'value', 'id', 'disabled', 'type', 'class', 'dir', 'tabindex'],
 'link'      : ['lang', 'style', 'target', 'title', 'media', 'charset', 'rev', 'hreflang', 'disabled', 'href', 'rel', 'id', 'type', 'class', 'dir'],
 'map'       : ['lang', 'style', 'title', 'id', 'class', 'dir'],
 'mark'      : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'marquee'   : ['dataformatas', 'accesskey', 'height', 'datafld', 'hspace', 'id', 'hidefocus', 'style', 'title', 'truespeed', 'unselectable', 'bgcolor', 'direction', 'scrollamount', 'class', 'lang', 'contenteditable', 'language', 'scrolldelay', 'datasrc', 'vspace', 'dir', 'behavior', 'width', 'loop', 'tabindex'],
 'math'      : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'menu'      : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'label', 'type', 'class', 'dir', 'tabindex'],
 'meta'      : ['lang', 'name', 'content', 'http-equiv', 'scheme', 'id', 'dir'],
 'meter'     : ['accesskey', 'high', 'optimum', 'id', 'style', 'spellcheck', 'min', 'label', 'low', 'hidden', 'type', 'form', 'max', 'class', 'lang', 'contenteditable', 'contextmenu', 'title', 'value', 'draggable', 'dir', 'tabindex'],
 'nav'       : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'nobr'      : ['style', 'contenteditable', 'title', 'unselectable', 'id', 'disabled', 'class', 'dir'],
 'noembed'   : ['style', 'title', 'class', 'id'],
 'noframes'  : ['lang', 'style', 'title', 'id', 'class', 'dir'],
 'noscript'  : ['lang', 'style', 'title', 'id', 'class', 'dir'],
 'object'    : ['classid', 'code', 'accesskey', 'usemap', 'height', 'datafld', 'codetype', 'hspace', 'archive', 'hidefocus', 'style', 'title', 'border', 'id', 'width', 'type', 'codebase', 'data', 'class', 'lang', 'name', 'standby', 'align', 'datasrc', 'vspace', 'unselectable', 'declare', 'dir', 'tabindex'],
 'ol'        : ['compact', 'hidefocus', 'style', 'contenteditable', 'lang', 'language', 'title', 'unselectable', 'accesskey', 'reversed', 'id', 'disabled', 'start', 'type', 'class', 'dir', 'tabindex'],
 'optgroup'  : ['lang', 'style', 'title', 'label', 'disabled', 'id', 'class', 'dir'],
 'option'    : ['lang', 'style', 'language', 'title', 'selected', 'value', 'label', 'disabled', 'id', 'class', 'dir'],
 'output'    : ['lang', 'style', 'contenteditable', 'form', 'for', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'tabindex', 'class', 'dir', 'name'],
 'p'         : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'align', 'dir', 'tabindex'],
 'param'     : ['dataformatas', 'name', 'valuetype', 'datasrc', 'value', 'datafld', 'type', 'id'],
 'pre'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'width', 'xml:space', 'wrap', 'class', 'dir', 'tabindex'],
 'progress'  : ['lang', 'style', 'contenteditable', 'form', 'contextmenu', 'max', 'accesskey', 'title', 'value', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'q'         : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'class', 'disabled', 'id', 'cite', 'dir', 'tabindex'],
 'rp'        : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'rt'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'name', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'ruby'      : ['lang', 'hidefocus', 'style', 'contenteditable', 'name', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 's'         : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'samp'      : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'script'    : ['defer', 'for', 'language', 'src', 'xml:space', 'charset', 'id', 'type', 'event'],
 'section'   : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'select'    : ['lang', 'hidefocus', 'style', 'multiple', 'name', 'language', 'title', 'unselectable', 'accesskey', 'datasrc', 'class', 'disabled', 'datafld', 'id', 'tabindex', 'align', 'dir', 'size'],
 'small'     : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'source'    : ['lang', 'src', 'style', 'contenteditable', 'contextmenu', 'media', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'type', 'class', 'dir', 'tabindex'],
 'span'      : ['lang', 'dataformatas', 'style', 'contenteditable', 'language', 'hidefocus', 'unselectable', 'accesskey', 'title', 'datasrc', 'id', 'datafld', 'class', 'dir', 'tabindex'],
 'strike'    : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'strong'    : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'style'     : ['lang', 'title', 'media', 'xml:space', 'disabled', 'type', 'id', 'dir'],
 'sub'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'summary'   : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'sup'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'svg'       : ['lang', 'style', 'contenteditable', 'contextmenu', 'accesskey', 'title', 'id', 'draggable', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'table'     : ['bordercolorlight', 'frame', 'cols', 'height', 'hspace', 'id', 'hidefocus', 'style', 'title', 'border', 'bgcolor', 'cellspacing', 'accesskey', 'bordercolor', 'rules', 'bordercolordark', 'background', 'class', 'lang', 'language', 'datapagesize', 'datasrc', 'summary', 'vspace', 'unselectable', 'cellpadding', 'width', 'dir', 'tabindex'],
 'tbody'     : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'class', 'char', 'bgcolor', 'valign', 'id', 'charoff', 'align', 'dir', 'tabindex'],
 'td'        : ['bordercolorlight', 'accesskey', 'height', 'char', 'nowrap', 'id', 'axis', 'hidefocus', 'style', 'rowspan', 'title', 'unselectable', 'bgcolor', 'colspan', 'scope', 'charoff', 'bordercolor', 'valign', 'bordercolordark', 'abbr', 'background', 'class', 'lang', 'language', 'align', 'headers', 'width', 'dir', 'tabindex'],
 'textarea'  : ['lang', 'hidefocus', 'style', 'rows', 'name', 'language', 'title', 'accesskey', 'datasrc', 'wrap', 'cols', 'disabled', 'datafld', 'readonly', 'id', 'class', 'dir', 'tabindex'],
 'tfoot'     : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'class', 'char', 'valign', 'id', 'charoff', 'align', 'dir', 'tabindex'],
 'th'        : ['bordercolorlight', 'accesskey', 'height', 'char', 'nowrap', 'id', 'axis', 'hidefocus', 'style', 'rowspan', 'title', 'unselectable', 'bgcolor', 'colspan', 'scope', 'charoff', 'bordercolor', 'valign', 'bordercolordark', 'abbr', 'background', 'class', 'lang', 'language', 'align', 'headers', 'dir', 'tabindex'],
 'thead'     : ['lang', 'hidefocus', 'style', 'language', 'title', 'unselectable', 'accesskey', 'class', 'char', 'valign', 'id', 'charoff', 'align', 'dir', 'tabindex'],
 'time'      : ['lang', 'style', 'contenteditable', 'pubdate', 'contextmenu', 'accesskey', 'title', 'datetime', 'draggable', 'id', 'spellcheck', 'hidden', 'class', 'dir', 'tabindex'],
 'title'     : ['lang', 'id', 'dir'],
 'tr'        : ['bordercolor', 'hidefocus', 'style', 'lang', 'language', 'title', 'bordercolorlight', 'accesskey', 'bordercolordark', 'class', 'char', 'bgcolor', 'valign', 'id', 'height', 'charoff', 'align', 'dir', 'tabindex'],
 'tt'        : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'disabled', 'class', 'dir', 'tabindex'],
 'u'         : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'ul'        : ['compact', 'hidefocus', 'style', 'contenteditable', 'lang', 'language', 'title', 'unselectable', 'accesskey', 'id', 'type', 'class', 'dir', 'tabindex'],
 'var'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex'],
 'video'     : ['lang', 'preload', 'style', 'contenteditable', 'contextmenu', 'poster', 'accesskey', 'title', 'height', 'draggable', 'width', 'tabindex', 'loop', 'id', 'spellcheck', 'hidden', 'src', 'class', 'dir', 'autoplay'],
 'wbr'       : ['id'],
 'xml'       : ['src', 'id'],
 'xmp'       : ['lang', 'hidefocus', 'style', 'contenteditable', 'language', 'title', 'unselectable', 'accesskey', 'id', 'class', 'dir', 'tabindex']}

HTML_ATTRIBUTES_VALUES = {
 'abbr'             : [],
 'above'            : [],
 'accept'           : ['text/html', '*', 'application/x-zip-compressed', 'application/msexcel', 'text/plain', 'application/rtf', 'application/pdf', 'application/msword'],
 'accept-charset'   : ['unknown', '*', 'ISO-8859-1'],
 'accesskey'        : [],
 'action'           : [],
 'align'            : ['right', 'center', 'bottom', 'baseline', 'top', 'absmiddle', 'middle', 'texttop', 'absbottom', 'left', 'justify'],
 'alink'            : [],
 'allowtransparency': ['yes', 'no'],
 'alt'              : [],
 'application'      : ['yes', 'no'],
 'archive'          : [],
 'autocomplete'     : ['on', 'off'],
 'autofocus'        : [],
 'autoplay'         : ['false', 'true'],
 'axis'             : [],
 'background'       : [],
 'balance'          : [],
 'behavior'         : ['slide', 'alternate', 'scroll'],
 'below'            : [],
 'bgcolor'          : [],
 'bgproperties'     : ['fixed'],
 'border'           : [],
 'bordercolor'      : [],
 'bordercolordark'  : [],
 'bordercolorlight' : [],
 'bottommargin'     : [],
 'cellpadding'      : [],
 'cellspacing'      : [],
 'challenge'        : [],
 'char'             : [],
 'charoff'          : [],
 'charset'          : ['UTF-8', 'HZ-GB-2312', '*', 'ISO-8859-15', 'ISO-2022-JP', 'ISO-8859-9', 'ISO-8859-8', 'ISO-8859-7', 'ISO-8859-6', 'ISO-8859-5', 'ISO-8859-4', 'ISO-8859-3', 'ISO-8859-2', 'ISO-8859-1', 'cp1255', 'cp1254', 'cp1257', 'cp1256', 'cp1251', 'cp1250', 'cp1253', 'cp1252', 'cp1258', 'ISO-2022-JP-2', 'Shift_JIS', 'ISO-8859-10', 'ISO-2022-KR'],
 'checked'          : ['checked'],
 'cite'             : [],
 'class'            : [],
 'clear'            : ['all', 'right', 'none', 'left'],
 'clip'             : [],
 'code'             : [],
 'codebase'         : [],
 'color'            : [],
 'cols'             : [],
 'colspan'          : [],
 'compact'          : ['compact'],
 'content'          : ['text/html; charset=ISO-2022-JP', 'text/html; charset=ISO-8859-9', 'text/html; charset=ISO-8859-8', 'text/html; charset=HZ-GB-2312', 'text/html; charset=ISO-8859-3', 'text/html; charset=ISO-8859-2', '*', 'text/html; charset=ISO-8859-7', 'text/html; charset=ISO-8859-6', 'text/html; charset=ISO-8859-5', 'text/html; charset=ISO-8859-4', 'text/html; charset=cp1250', 'text/html; charset=cp1253', 'text/html; charset=cp1258', 'text/html; charset=Shift_JIS', 'text/html; charset=ISO-8859-10', 'text/html; charset=cp1251', 'text/html; charset=UTF-8', 'text/html; charset=iso-8859-1', 'text/html; charset=cp1252', 'text/html; charset=cp1255', 'text/html; charset=cp1254', 'text/html; charset=ISO-8859-15', 'text/html; charset=cp1256', 'text/html; charset=cp1257', 'text/html; charset=ISO-2022-JP-2', 'text/html', 'text/html; charset=ISO-2022-KR'],
 'contenteditable'  : ['true', 'false', 'inherit'],
 'contextmenu'      : [],
 'controls'         : ['false', 'true'],
 'coords'           : [],
 'data'             : [],
 'datafld'          : [],
 'dataformatas'     : ['text', 'html'],
 'datapagesize'     : [],
 'datasrc'          : [],
 'datetime'         : [],
 'declare'          : ['declare'],
 'defer'            : ['defer'],
 'dir'              : ['ltr', 'rtl'],
 'direction'        : ['down', 'right', 'up', 'left'],
 'disabled'         : ['false', 'true'],
 'draggable'        : ['false', 'true', 'auto'],
 'dynsrc'           : [],
 'enctype'          : ['*', 'multipart/form-data', 'text/plain', 'application/x-www-form-urlencoded'],
 'event'            : [],
 'face'             : [],
 'for'              : [],
 'form'             : [],
 'frame'            : ['box', 'vsides', 'hsides', 'rhs', 'below', 'lhs', 'above', 'border', 'void'],
 'frameborder'      : ['1', '0', 'yes', 'no'],
 'framespacing'     : [],
 'galleryimg'       : ['false', 'yes', 'true', 'no'],
 'headers'          : [],
 'height'           : [],
 'hidden'           : ['false', 'true'],
 'hidefocus'        : ['false', 'true'],
 'high'             : [],
 'href'             : [],
 'hreflang'         : [],
 'hspace'           : [],
 'http-equiv'       : [],
 'icon'             : [],
 'id'               : [],
 'keytype'          : [],
 'label'            : [],
 'lang'             : [],
 'language'         : ['JavaScript', 'JScript', 'VBScript', '*', 'vbscript', 'vbs', 'jscript', 'JavaScript1.1', 'javascript', 'JavaScript1.2', 'php'],
 'left'             : [],
 'leftmargin'       : [],
 'link'             : [],
 'longdesc'         : [],
 'loop'             : [],
 'low'              : [],
 'lowsrc'           : [],
 'marginheight'     : [],
 'marginwidth'      : [],
 'max'              : [],
 'maxlength'        : [],
 'mayscript'        : [],
 'media'            : ['all', 'projection', 'braille', 'screen', '*', 'other', 'print', 'aural'],
 'method'           : ['post', 'get'],
 'methods'          : [],
 'min'              : [],
 'multiple'         : ['multiple'],
 'name'             : [],
 'nohref'           : ['nohref'],
 'noresize'         : ['noresize'],
 'noshade'          : ['noshade'],
 'nowrap'           : ['nowrap'],
 'object'           : [],
 'open'             : ['false', 'true'],
 'optimum'          : [],
 'overflow'         : ['none', 'clip'],
 'pagex'            : [],
 'pagey'            : [],
 'palette'          : ['foreground', 'background'],
 'pluginspage'      : [],
 'point-size'       : [],
 'poster'           : [],
 'preload'          : ['auto', 'none', 'metadata'],
 'profile'          : [],
 'pubdate'          : ['false', 'true'],
 'radiogroup'       : [],
 'readonly'         : ['readonly'],
 'rel'              : ['chapter', 'index', 'help', 'copyright', 'start', 'bookmark', 'section', 'alternate', 'next', 'glossary', 'stylesheet', 'subsection', 'prev', 'contents'],
 'rev'              : ['chapter', 'index', 'help', 'copyright', 'start', 'bookmark', 'section', 'alternate', 'next', 'glossary', 'stylesheet', 'subsection', 'prev', 'contents'],
 'reversed'         : [],
 'rightmargin'      : [],
 'rows'             : [],
 'rowspan'          : [],
 'rules'            : ['none', 'all', 'rows', 'cols', 'groups'],
 'scheme'           : [],
 'scope'            : ['row', 'col', 'rowgroup', 'colgroup'],
 'scroll'           : ['auto', 'yes', 'no'],
 'scrollamount'     : [],
 'scrolldelay'      : [],
 'scrolling'        : ['auto', 'yes', 'no'],
 'selected'         : ['selected'],
 'shape'            : ['default', 'circle', 'rect', 'poly'],
 'size'             : ['*', '1', '3', '2', '5', '4', '7', '6'],
 'span'             : [],
 'spellcheck'       : ['default', 'false', 'true'],
 'src'              : [],
 'standby'          : [],
 'start'            : [],
 'style'            : [],
 'summary'          : [],
 'tabindex'         : [],
 'target'           : ['_self', '_top', '*', '_blank', '_parent'],
 'text'             : [],
 'title'            : [],
 'top'              : [],
 'truespeed'        : ['truespeed'],
 'type'             : ['A', 'checkbox', 'tel', 'color', 'text', 'image', 'number', 'datetime', 'text/tcl', 'disc', 'radio', 'file', 'application/x-shockwave-flash', '*', 'submit', '1', 'I', 'application/javascript', 'square', 'text/php', 'hidden', 'email', 'week', 'a', 'month', 'date', 'password', 'circle', 'datetime-local', 'reset', 'search', 'text/javascript', 'url', 'button', 'text/jscript', 'i', 'range', 'text/vbscript', 'time', 'text/css'],
 'units'            : ['em', 'px'],
 'unselectable'     : ['on', 'off'],
 'urn'              : [],
 'usemap'           : [],
 'valign'           : ['middle', 'top', 'center', 'baseline', 'bottom'],
 'value'            : [],
 'valuetype'        : ['ref', 'object', 'data'],
 'visibility'       : ['hidden', 'shown', 'inherit'],
 'vlink'            : [],
 'volume'           : [],
 'vspace'           : [],
 'weight'           : ['200', '900', '600', '300', '700', '400', '100', '800', '500'],
 'width'            : [],
 'wrap'             : ['off', 'hard', 'soft'],
 'xml:space'        : ['preserve'],
 'xmlns'            : ['http://www.w3.org/1999/xhtml'],
 'z-index'          : []}